version: '3.8'

services:
  slack-bot:
    build: .
    container_name: slack-task-bot
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

  redis:
    image: redis:7-alpine
    container_name: slack-bot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  redis-data: